### ISSUE TITLE
Private room bug

### ISSUE THREAD

**Issue by simonpankovski** [luvuong-le/node-vue-chat#10]
Just checking out your project and I think it's fantastic, just wanted to let you know that the room ids are visible on the client side when you inspect the anchor tags and that anyone can join a private room just by copying the id

**Comment by luvuong-le** [comment]
@simonpankovski 

Thanks for pointing this issue out! 

I've originally had some checks in place in case a user would copy the id to boot (redirect) them out if they weren't supposed to have access as you said but it seems I overlooked it with my checks
