### ISSUE TITLE
Cant assign socket connection to vuex state

### ISSUE THREAD

**Issue by gkn06** [luvuong-le/node-vue-chat#5]
I tried storing the socket connection in Vuex state like you did. But I am facing this error.

`Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js?2f62:90)
    at Vue.store._vm.$watch.deep (vuex.esm.js?2f62:774)
    at Watcher.run (vue.runtime.esm.js?2b0e:4562)
    at Watcher.update (vue.runtime.esm.js?2b0e:4536)
    at Dep.notify (vue.runtime.esm.js?2b0e:730)
    at WS.reactiveSetter [as writable] (vue.runtime.esm.js?2b0e:1055)
    at eval (websocket.js?0882:218)`

Can you help me to solve this issue? Is this issue related to Vue version?

**Comment by gkn06** [comment]
I found the issue. I have enabled [strict mode in Vuex](https://vuex.vuejs.org/guide/strict.html), that's why I faced that error.
Is it a good practice to store the socket connection in Vuex state?

**Comment by luvuong-le** [comment]
Hi gnk06,

Glad to hear you were able to find the issue and resolve it!

I'm not 100% sure if it's considered best practice and you don't have to use Vuex at all although what I can say is that I found it provided a cleaner way to interact with and reuse the socket connection in a single data store. 

Though I'm sure there are many other ways to approach this

Another thing to mention, there is also a fairly popular library out there: **vue-socket.io** which by the looks also has an option of using Vuex integration and may be able to help you

You should go with an approach that works well for you whether that would be Vuex or another method

**Comment by luvuong-le** [comment]
Alternatively, you might also want to instead of using Vuex, is to create a service file ie **websocket.js** and export your created websocket instance there and import that instance into each component you will need it in

In the end, I'm sure there are better ways than I initially chose to implement :)

**Comment by gkn06** [comment]
Thanks for the explanation Luvuong-le.
For connections to multiple server vue-socket.io has some issues. The project which am working on needs this feature. I can achieve that based on your implementation.
Previously I tried connecting socket io from component. But for every component change new socket connection was created. And that's overhead in server.
That's why I considered your approach, by maintaining connection state and reusing the same.

Maybe I should try the other approach (service file) you said.

Thanks again for making this awesome
